apiVersion: v1
kind: Service
metadata:
  name: vita-wise-api-service
  namespace: vita-wise
  labels:
    app: vita-wise-api
spec:
  selector:
    app: vita-wise-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: vita-wise-api-nodeport
  namespace: vita-wise
  labels:
    app: vita-wise-api
spec:
  selector:
    app: vita-wise-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
  type: NodePort
